import React from 'react';
import PropTypes from 'prop-types';

import { Row, Col, Container } from 'react-bootstrap';

import Bigstat from '../Bigstat';

const SectionStats = () => (
	<section className="section-stats text-light">
		<Container>
			<h2 className="font-weight-light mb-5 text-center">Token Stats</h2>
			<Row>
				<Col md="6" className="pb-4">
					<Bigstat id="price">
						TRIB gets more expensive as the supply increases and cheaper as supply decreases.
						{' '}
						<strong>The contract provides infinite liquidity</strong>
						{' '}
						to users.
					</Bigstat>
				</Col>
				<Col md="6" className="pb-4">
					<Bigstat id="floor">
						Burned tokens can’t be sold back to the contract. This effectively creates a price floor
						{' '}
						<strong>which is constantly being raised</strong>
						{' '}
						every time tokens get burned.
					</Bigstat>
				</Col>
			</Row>
			<Row>
				<Col md="6" className="pb-4">
					<Bigstat id="totalBurned">
						Tokens are burned from the interest that is generated by the pool. Everytime TRIB is
						burned
						the price floor is increased.
						{' '}
						<strong>TRIB’s price cannot go below the floor</strong>
						.
					</Bigstat>
				</Col>
				<Col md="6" className="pb-4">
					<Bigstat id="supply">
						A higher supply means more DAI generating interest for the system.
						The interest is used to mint and burn TRIB tokens,
						{' '}
						<strong>increasing its price</strong>
						.
					</Bigstat>
				</Col>
			</Row>
		</Container>
	</section>
);

SectionStats.propTypes = {
	drizzle: PropTypes.shape({
		contracts: PropTypes.shape({
			Contribute: PropTypes.object,
			ViewContribute: PropTypes.object,
		}),
		web3: PropTypes.object,
	}),
	drizzleState: PropTypes.shape({
		contracts: PropTypes.shape({
			Contribute: PropTypes.object,
			ViewContribute: PropTypes.object,
		}),
	}),
};

SectionStats.defaultProps = {
	drizzle: null,
	drizzleState: null,
};

export default SectionStats;
